import 'package:flutter/material.dart';

/// Kilto color palette.
///
/// The canonical scale is the zinc neutral ramp ([zinc950]..[zinc50]) plus
/// the brand & status tokens grouped below. Legacy aliases ([navy], [teal],
/// [grey], etc.) are kept for screens that haven't been migrated yet.
class KiltoColors {
  // --- Zinc neutral ramp (canonical) ---
  static const zinc950 = Color(0xFF09090B);
  static const zinc900 = Color(0xFF18181B);
  static const zinc800 = Color(0xFF27272A);
  static const zinc700 = Color(0xFF3F3F46);
  static const zinc600 = Color(0xFF52525B);
  static const zinc500 = Color(0xFF71717A);
  static const zinc400 = Color(0xFFA1A1AA);
  static const zinc300 = Color(0xFFD4D4D8);
  static const zinc200 = Color(0xFFE4E4E7);
  static const zinc100 = Color(0xFFF4F4F5);
  static const zinc50 = Color(0xFFFAFAFA);

  // --- Surfaces ---
  static const bg = zinc50;
  static const surface = Color(0xFFFFFFFF);
  static const surfaceAlt = zinc100;
  static const border = zinc200;
  static const borderLight = zinc100;

  // --- Text ---
  static const textPrimary = zinc950;
  static const textSecondary = zinc600;
  static const textTertiary = zinc500;

  // --- Brand (Kilto default; clinic accent overrides via ClinicAccentTheme) ---
  static const brandPrimary = Color(0xFF0A0A0A);
  static const brandHover = Color(0xFF262626);
  static const brandLight = zinc100;
  static const onBrand = Color(0xFFFAFAFA);

  // --- Status ---
  static const success = Color(0xFF10B981);
  static const successLight = Color(0xFFECFDF5);
  static const warning = Color(0xFFF59E0B);
  static const warningLight = Color(0xFFFFFBEB);
  static const error = Color(0xFFEF4444);
  static const errorLight = Color(0xFFFEF2F2);
  static const info = Color(0xFF3B82F6);
  static const infoLight = Color(0xFFEFF6FF);
  static const violet = Color(0xFF8B5CF6);
  static const violetLight = Color(0xFFF5F3FF);

  // --- Legacy aliases (do not add new usages; migrate when touching a file) ---
  @Deprecated('Use textPrimary') static const navy = textPrimary;
  @Deprecated('Use textPrimary') static const navyLight = textPrimary;
  @Deprecated('Use brandPrimary') static const teal = brandPrimary;
  @Deprecated('Use brandHover') static const tealDark = brandHover;
  @Deprecated('Use brandLight') static const tealLight = brandLight;
  @Deprecated('Use surface') static const white = surface;
  @Deprecated('Use bg') static const grey = bg;
  @Deprecated('Use border') static const greyMid = border;
  @Deprecated('Use textSecondary') static const greyText = textSecondary;
  @Deprecated('Use textPrimary') static const dark = textPrimary;
  @Deprecated('Use success') static const green = success;
  @Deprecated('Use successLight') static const greenLight = successLight;
  @Deprecated('Use warning') static const yellow = warning;
  @Deprecated('Use warningLight') static const yellowLight = warningLight;
  @Deprecated('Use error') static const red = error;
  @Deprecated('Use errorLight') static const redLight = errorLight;
  @Deprecated('Use info') static const blue = info;
  @Deprecated('Use infoLight') static const blueLight = infoLight;
}

/// Corner radii used across the app.
class KiltoRadii {
  static const xsmall = 9.0;
  static const small = 11.0;
  static const medium = 14.0;
  static const large = 16.0;
  static const xlarge = 22.0;
  static const pill = 100.0;
}

/// Pre-baked soft shadows for cards and CTAs.
///
/// All values use a single 0px-x / 8px-y offset + 22px blur — the same recipe
/// the mockup uses for every elevated surface. Color-tinted variants are
/// generated by [hero] for the gradient hero cards.
class KiltoShadows {
  static const card = <BoxShadow>[
    BoxShadow(blurRadius: 22, offset: Offset(0, 8), color: Color(0x14000000)),
  ];

  static const ctaPrimary = <BoxShadow>[
    BoxShadow(blurRadius: 22, offset: Offset(0, 8), color: Color(0x520A0A0A)),
  ];

  static List<BoxShadow> hero(Color accent) => <BoxShadow>[
        BoxShadow(
          blurRadius: 22,
          offset: const Offset(0, 8),
          color: accent.withValues(alpha: 0.22),
        ),
      ];
}

/// Font family constants. Use [familyHeading] for display / heading text and
/// [familyBody] for everything else.
class KiltoFonts {
  static const familyHeading = 'Outfit';
  static const familyBody = 'DMSans';
}

class KiltoTheme {
  static ThemeData get light => ThemeData(
        useMaterial3: true,
        fontFamily: KiltoFonts.familyBody,
        scaffoldBackgroundColor: KiltoColors.bg,
        colorScheme: const ColorScheme.light(
          primary: KiltoColors.brandPrimary,
          onPrimary: KiltoColors.onBrand,
          secondary: KiltoColors.textPrimary,
          onSecondary: KiltoColors.onBrand,
          surface: KiltoColors.surface,
          onSurface: KiltoColors.textPrimary,
          surfaceContainerHighest: KiltoColors.borderLight,
          outline: KiltoColors.border,
          error: KiltoColors.error,
          onError: KiltoColors.onBrand,
        ),
        appBarTheme: const AppBarTheme(
          backgroundColor: KiltoColors.surface,
          foregroundColor: KiltoColors.textPrimary,
          elevation: 0,
          surfaceTintColor: KiltoColors.surface,
          titleTextStyle: TextStyle(
            fontFamily: KiltoFonts.familyHeading,
            fontSize: 17,
            fontWeight: FontWeight.w800,
            letterSpacing: -0.3,
            color: KiltoColors.textPrimary,
          ),
        ),
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            backgroundColor: KiltoColors.brandPrimary,
            foregroundColor: KiltoColors.onBrand,
            iconColor: KiltoColors.onBrand,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(KiltoRadii.medium),
            ),
            padding:
                const EdgeInsets.symmetric(horizontal: 24, vertical: 16),
            textStyle: const TextStyle(
              fontFamily: KiltoFonts.familyHeading,
              fontWeight: FontWeight.w800,
              fontSize: 14,
              letterSpacing: -0.2,
            ),
            elevation: 6,
            shadowColor: const Color(0x520A0A0A),
          ),
        ),
        outlinedButtonTheme: OutlinedButtonThemeData(
          style: OutlinedButton.styleFrom(
            foregroundColor: KiltoColors.textPrimary,
            side: const BorderSide(color: KiltoColors.border, width: 1.5),
            backgroundColor: KiltoColors.surface,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(KiltoRadii.medium),
            ),
            padding:
                const EdgeInsets.symmetric(horizontal: 18, vertical: 14),
            textStyle: const TextStyle(
              fontFamily: KiltoFonts.familyHeading,
              fontWeight: FontWeight.w700,
              fontSize: 13,
            ),
          ),
        ),
        textButtonTheme: TextButtonThemeData(
          style: TextButton.styleFrom(
            foregroundColor: KiltoColors.textPrimary,
            textStyle: const TextStyle(
              fontFamily: KiltoFonts.familyBody,
              fontWeight: FontWeight.w600,
              fontSize: 13,
            ),
          ),
        ),
        cardTheme: CardThemeData(
          color: KiltoColors.surface,
          surfaceTintColor: KiltoColors.surface,
          elevation: 0,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(KiltoRadii.medium),
            side: const BorderSide(color: KiltoColors.border),
          ),
        ),
        inputDecorationTheme: InputDecorationTheme(
          filled: true,
          fillColor: KiltoColors.surface,
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(KiltoRadii.small),
            borderSide: const BorderSide(color: KiltoColors.border),
          ),
          enabledBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(KiltoRadii.small),
            borderSide: const BorderSide(color: KiltoColors.border),
          ),
          focusedBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(KiltoRadii.small),
            borderSide:
                const BorderSide(color: KiltoColors.brandPrimary, width: 1.5),
          ),
          errorBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(KiltoRadii.small),
            borderSide: const BorderSide(color: KiltoColors.error),
          ),
          hintStyle: const TextStyle(
            color: KiltoColors.textTertiary,
            fontFamily: KiltoFonts.familyBody,
            fontWeight: FontWeight.w500,
            fontSize: 13,
          ),
          labelStyle: const TextStyle(
            color: KiltoColors.textSecondary,
            fontFamily: KiltoFonts.familyBody,
            fontWeight: FontWeight.w500,
          ),
          contentPadding:
              const EdgeInsets.symmetric(horizontal: 14, vertical: 14),
        ),
        bottomNavigationBarTheme: const BottomNavigationBarThemeData(
          backgroundColor: KiltoColors.surface,
          selectedItemColor: KiltoColors.brandPrimary,
          unselectedItemColor: KiltoColors.textTertiary,
          type: BottomNavigationBarType.fixed,
          elevation: 0,
          selectedLabelStyle: TextStyle(
            fontFamily: KiltoFonts.familyHeading,
            fontWeight: FontWeight.w800,
            fontSize: 10,
            letterSpacing: 0.2,
          ),
          unselectedLabelStyle: TextStyle(
            fontFamily: KiltoFonts.familyBody,
            fontWeight: FontWeight.w500,
            fontSize: 10,
          ),
        ),
        dividerTheme: const DividerThemeData(
          color: KiltoColors.border,
          thickness: 1,
          space: 1,
        ),
        chipTheme: ChipThemeData(
          backgroundColor: KiltoColors.borderLight,
          labelStyle: const TextStyle(
            fontFamily: KiltoFonts.familyBody,
            color: KiltoColors.textPrimary,
            fontWeight: FontWeight.w600,
            fontSize: 11.5,
          ),
          side: const BorderSide(color: KiltoColors.border),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(KiltoRadii.pill),
          ),
          padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
        ),
      );
}
